fix cve

diff --git a/Dockerfile.mysql80 b/Dockerfile.mysql80
--- a/Dockerfile.mysql80
+++ b/Dockerfile.mysql80
@@ -13,30 +13,31 @@ RUN set -eux; \
 
 # add gosu for easy step-down from root
 # https://github.com/tianon/gosu/releases
-ENV GOSU_VERSION 1.14
-RUN set -eux; \
-# TODO find a better userspace architecture detection method than querying the kernel
-	arch="$(uname -m)"; \
-	case "$arch" in \
-		aarch64) gosuArch='arm64' ;; \
-		x86_64) gosuArch='amd64' ;; \
-		*) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
-	esac; \
-	curl -fL -o /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$gosuArch.asc"; \
-	curl -fL -o /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$gosuArch"; \
-	export GNUPGHOME="$(mktemp -d)"; \
-	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
-	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
-	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
-	chmod +x /usr/local/bin/gosu; \
-	gosu --version; \
-	gosu nobody true
+# ENV GOSU_VERSION 1.14
+# RUN set -eux; \
+# # TODO find a better userspace architecture detection method than querying the kernel
+# 	arch="$(uname -m)"; \
+# 	case "$arch" in \
+# 		aarch64) gosuArch='arm64' ;; \
+# 		x86_64) gosuArch='amd64' ;; \
+# 		*) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+# 	esac; \
+# 	curl -fL -o /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$gosuArch.asc"; \
+# 	curl -fL -o /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$gosuArch"; \
+# 	export GNUPGHOME="$(mktemp -d)"; \
+# 	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+# 	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+# 	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+# 	chmod +x /usr/local/bin/gosu; \
+# 	gosu --version; \
+# 	gosu nobody true
 
 RUN set -eux; \
 	microdnf install -y \
 		gzip \
 		openssl \
 		xz \
+		procps-ng \
 		zstd \
 # Oracle Linux 8+ is very slim :)
 		findutils \
@@ -86,26 +87,26 @@ RUN set -eux; \
 	mysqld --version; \
 	mysql --version
 
-RUN set -eu; \
-	. /etc/os-release; \
-	{ \
-		echo '[mysql-tools-community]'; \
-		echo 'name=MySQL Tools Community'; \
-		echo "baseurl=https://repo.mysql.com/yum/mysql-tools-community/el/${VERSION_ID%%[.-]*}/\$basearch/"; \
-		echo 'enabled=1'; \
-		echo 'gpgcheck=1'; \
-		echo 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql'; \
-# https://github.com/docker-library/mysql/pull/680#issuecomment-825930524
-		echo 'module_hotfixes=true'; \
-	} | tee /etc/yum.repos.d/mysql-community-tools.repo
-ENV MYSQL_SHELL_VERSION 8.0.29-1.el8
-RUN set -eux; \
-	microdnf install -y "mysql-shell-$MYSQL_SHELL_VERSION" \
-    procps-ng; \
-	microdnf clean all; \
-	\
-	mysqlsh --version
-
+# RUN set -eu; \
+# 	. /etc/os-release; \
+# 	{ \
+# 		echo '[mysql-tools-community]'; \
+# 		echo 'name=MySQL Tools Community'; \
+# 		echo "baseurl=https://repo.mysql.com/yum/mysql-tools-community/el/${VERSION_ID%%[.-]*}/\$basearch/"; \
+# 		echo 'enabled=1'; \
+# 		echo 'gpgcheck=1'; \
+# 		echo 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql'; \
+# # https://github.com/docker-library/mysql/pull/680#issuecomment-825930524
+# 		echo 'module_hotfixes=true'; \
+# 	} | tee /etc/yum.repos.d/mysql-community-tools.repo
+# ENV MYSQL_SHELL_VERSION 8.0.29-1.el8
+# RUN set -eux; \
+# 	microdnf install -y "mysql-shell-$MYSQL_SHELL_VERSION" \
+#     procps-ng; \
+# 	microdnf clean all; \
+# 	\
+# 	mysqlsh --version
+RUN microdnf  --enablerepo='ol8_appstream' --enablerepo='ol8_baseos_latest' --disablerepo='mysql8.0-server-minimal' update -y;mysql --version
 VOLUME /var/lib/mysql
 ADD audit_log.so /usr/lib64/mysql/plugin/
 COPY ps-entry.sh /docker-entrypoint.sh
